---
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0700'

- name: Create K3s config directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Deploy K3s config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: '0644'

- name: Install K3s
  ansible.builtin.command:
    cmd: /tmp/k3s_install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_SKIP_START: "true"
  changed_when: false

- name: Enable and start K3s service
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true
