# Copy this file to secrets.yml and fill in the values.
# secrets.yml is ignored by git.

# Password for user 'arjun'. Generate with: mkpasswd -m sha-512
user_password: "$6$..."

# Shared secret for K3s cluster.
k3s_token: "your_secure_token_here"

# Public SSH Key for user 'arjun'.
user_ssh_key: "ssh-rsa ..."
